# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a3e3385acc7d69649f217fa4f2fcd21736432acadcf4fc9732e46dd42da9ef943c77a9456c13535d68db25459f62c96405c22f0fb550c86470a4cc898808844

test:
  secret_key_base: 717248863633050d3ec279ff52a76e4d8bf81f8038a5fa4e920e2877d0673fd31ea0e9fa0aa1101585ef900cfc13ebb729b3c407d9b7031a29b8baa6e7ae8453

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
